airline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("flights/", include("flights.urls")),
    path("users/", include("users.urls"))
]

auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register_view, name="register"),
    path("create-listing", views.create_listing_view, name="create_listing"),
    path("watchlist", views.watchlist_view, name="watchlist"),
    path("categories", views.categories_view, name="categories"),
    path("category/<str:category>", views.listings_by_category_view, name="listings_by_category"),
    path("listing/<int:listing_id>", views.listing_view, name="listing")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    def __str__(self):
        return f"{self.username}"


class Category(models.Model):
    title = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.title}"


class AuctionListing(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="listings")
    title = models.CharField(max_length=64)
    description = models.CharField(max_length=1000)
    highest_bid = models.IntegerField()
    image_url = models.URLField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="listings", blank=True, null=True)

    def __str__(self):
        return f"{self.title} from {self.owner}"


class Bid(models.Model):
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bids")
    listing = models.ForeignKey(AuctionListing, on_delete=models.CASCADE, related_name="bids")
    amount = models.IntegerField()

    def __str__(self):
        return f"{self.amount} from {self.bidder} for {self.listing}"


class Comment(models.Model):
    commenter = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    listing = models.ForeignKey(AuctionListing, on_delete=models.CASCADE, related_name="comments")
    content = models.CharField(max_length=256)

    def __str__(self):
        return f"{self.commenter} says: {self.content}"


class Watchlist(models.Model):
    watcher = models.ForeignKey(User, on_delete=models.CASCADE, related_name="watched_listings")
    listing = models.ForeignKey(AuctionListing, on_delete=models.CASCADE, related_name="watcher")

    def __str__(self):
        return f"{self.watcher} watches {self.listing}"

auctions/views.py
from django import forms
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import User, Category, AuctionListing


def index(request):
    return HttpResponseRedirect(reverse("auctions:listings_by_category", kwargs={"category": "all"}))


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


@login_required(login_url="auctions:login")
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")


@login_required(login_url="auctions:login")
def create_listing_view(request):
    if request.method == "POST":
        title_form = TitleForm(request.POST)
        description_form = DescriptionForm(request.POST)
        bidding_form = BiddingForm(request.POST)
        print(f"post = {request.POST}")
        if title_form.is_valid() and description_form.is_valid() and bidding_form.is_valid():
            title = request.POST["title_form"]
            description = request.POST["description_area"]
            starting_bid = request.POST["bidding_form"]
            image_url = request.POST["image_url_form"]
            category = request.POST["category_form"]
            user = request.user

            try:
                category = Category.objects.get(title=category)
                new_listing = AuctionListing(title=title, description=description, highest_bid=starting_bid,
                                             image_url=image_url, category=category, owner=user)
                new_listing.save()
            except Category.DoesNotExist:
                new_listing = AuctionListing(title=title, description=description, highest_bid=starting_bid,
                                             image_url=image_url, category=None, owner=user)
                new_listing.save()

    return render(request, "auctions/create_listing.html", {
        "title_form": TitleForm,
        "description_area": DescriptionForm,
        "bidding_form": BiddingForm,
        "image_url_form": ImageURLForm,
        "categories": Category.objects.all()
    })


@login_required(login_url="auctions:login")
def watchlist_view(request):
    return render(request, "auctions/watchlist.html")


@login_required(login_url="auctions:login")
def categories_view(request):
    categories = Category.objects.all()
    return render(request, "auctions/categories.html", {
        "categories": categories
    })


def listings_by_category_view(request, category):
    if category == "all":
        # Show all listings
        listings = AuctionListing.objects.all()
    else:
        try:
            category = Category.objects.get(title=category)
            listings = AuctionListing.objects.filter(category=category)
        except Category.DoesNotExist:
            return render(request, "auctions/listings_by_category.html", {
                "error_message": "No category found by that name"
            })
        except AuctionListing.DoesNotExist:
            return render(request, "auctions/listings_by_category.html", {
                "error_message": "No listings for this category"
            })
    return render(request, "auctions/listings_by_category.html", {
        "category": category,
        "listings": listings
    })


@login_required(login_url="auctions:login")
def listing_view(request, listing_id):
    listing = AuctionListing.objects.get(pk=listing_id)
    return render(request, "auctions/listing.html", {
        "listing": listing,
        "bidding_form": BiddingForm,
        "comment_form": CommentForm
    })


class DescriptionForm(forms.Form):
    description_area = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "Description"}), label="")


class TitleForm(forms.Form):
    title_form = forms.CharField(label="", max_length=64, widget=forms.TextInput(attrs={"placeholder": "Title"}))


class BiddingForm(forms.Form):
    bidding_form = forms.IntegerField(min_value=1, help_text="€", label="Bid")


class ImageURLForm(forms.Form):
    image_url_form = forms.URLField(label="Image URL", widget=forms.URLInput(attrs={"placeholder": "(optional)"}),
                                    required=False)


class CommentForm(forms.Form):
    comment_area = forms.CharField(widget=forms.Textarea, label="")

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block title %}
	Categories
{% endblock %}

{% block body %}
	<h2>All categories:</h2>
	<ul>
		{% for category in categories %}
			<li>
				<form method="post">
					<a href="{% url "auctions:listings_by_category" category %}">{{ category }}</a>
				</form>
			</li>
		{% empty %}
			<li>No categories available</li>
		{% endfor %}
	</ul>
{% endblock %}

auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}

{% block title %}
	Create Listing
{% endblock %}

{% block body %}
	<h3>Create new listing:</h3>
	<form method="post"
		  action="{% url "auctions:create_listing" %}">
		{% csrf_token %}
		<div>{{ title_form.as_p }}</div>
		<div>{{ description_area.as_p }}</div>
		<div>{{ bidding_form.as_p }}</div>
		<div>{{ image_url_form.as_p }}</div>
		<div>
			<p>
				<label for="select">Category:</label>
				<select id="select"
						name="category_form">
					<option selected>(optional)
					</option>
					{% for category in categories %}
						<option>{{ category }}</option>
					{% endfor %}
				</select>
			</p>
		</div>
		<input type="submit"
			   name="create listing"
			   value="Create listing"></form>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<title>{% block title %}Auctions{% endblock %}</title>
		<link rel="stylesheet"
			  href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
			  integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
			  crossorigin="anonymous">
		<link href="{% static 'auctions/styles.css' %}"
			  rel="stylesheet">
	</head>
	<body class="container">
		<h1>Auctions</h1>
		<div>
			{% if user.is_authenticated %}
				Signed in as <strong>{{ user.username }}</strong>.
			{% else %}
				Not signed in.
			{% endif %}
		</div>
		<ul class="nav">
			<li class="nav-item">
				<a class="nav-link"
				   href="{% url "auctions:index" %}">See active listings
				</a>
			</li>
			{% if user.is_authenticated %}
				<li class="nav-item">
					<a class="nav-link"
					   href="{% url "auctions:logout" %}">Log Out
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link"
					   href="{% url "auctions:create_listing" %}">Create new listing
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link"
					   href="{% url "auctions:watchlist" %}">See your Watchlist
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link"
					   href="{% url "auctions:categories" %}">See all categories
					</a>
				</li>
			{% else %}
				<li class="nav-item">
					<a class="nav-link"
					   href="{% url "auctions:login" %}">Log In
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link"
					   href="{% url "auctions:register" %}">Register
					</a>
				</li>
			{% endif %}
		</ul>
		<hr>
		{% block body %}
		{% endblock %}
	</body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block title %}
	{{ listing.title }}
{% endblock %}

{% block body %}
	<div><h2>{{ listing.title }}</h2></div>
	<div><h5>By {{ listing.owner }}</h5></div>
	<div><p><img src="{{ listing.image_url }}"
				 alt="No picture available"
				 height="500"></p></div>
	<b>Description:</b>
	<p>{{ listing.description }}</p>
	<b>Highest bid:</b>
	<p>{{ listing.highest_bid }} €</p>
	<b>Make a bid:</b>
	{{ bidding_form.as_p }}
	{% if user not in listing.watcher %}
		<div></div>
		<p>
		<form name="add_to_watchlist_form"
			  method="post"
			  action="{% url "auctions:listing" listing.id %}">
			{% csrf_token %}
			<button name="add_to_watchlist_button"
					type="submit"
					class="btn btn-outline-primary">Add to watchlist
			</button>
		</form>
		</p>
		</div>
	{% endif %}
	{% if user == listing.owner %}
		<div><p>
			<form name="close_listing_form"
				  action="{% url "auctions:listing" listing.id %}"
				  method="post">
				{% csrf_token %}
				<button name="close_listing_button"
						type="submit"
						class="btn-outline-danger btn">Close listing
				</button>
			</form>
			</p></div>
	{% endif %}
	<div><p>See if you won the auction</p></div>
	<b>Comment as {{ user }}:</b><br>
	<form name="post_comment_form"
		  action="{% url "auctions:listing" listing.id %}"
		  method="post">
		{% csrf_token %}
		{% csrf_token %}
		{{ comment_form }}
		<br>
		<button name="post_comment_button"
				class="btn btn-outline-primary"
				type="submit">Post comment
		</button>
	</form>
	<b>User say:</b><br>
	{% for comment in comments %}
		<b>{{ comment.commenter }}</b>
		<p>{{ comment }}</p>
		<hr>
	{% empty %}
		<i>...be the first to comment</i>
	{% endfor %}
{% endblock %}

auctions/templates/auctions/listings_by_category.html
{% extends "auctions/layout.html" %}

{% block title %}
	{% if error_message %}
		{{ error_message }}
	{% else %}
		{{ category }}
	{% endif %}
{% endblock %}

{% block body %}
	{% if error_message %}
		<h3>{{ error_message }}</h3>
	{% else %}
		{% for listing in listings %}
			<h3>
				<a href="{% url "auctions:listing" listing.id %}">{{ listing }}</a>
			</h3>
			<img src="{{ listing.image_url }}"
				 alt="Unable to load photo."
				 height="350">
			<br>
			<b>Description:</b>
			<p>{{ listing.description }}</p>
			<b>Current bid:</b>
			<p>{{ listing.highest_bid }} €</p>
			<hr>
		{% endfor %}
	{% endif %}
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

	<h2>Login</h2>

	{% if message %}
		<div>{{ message }}</div>
	{% endif %}

	<form action="{% url 'auctions:login' %}"
		  method="post">
		{% csrf_token %}
		<div class="form-group">
			<input autofocus
				   class="form-control"
				   type="text"
				   name="username"
				   placeholder="Username">
		</div>
		<div class="form-group">
			<input class="form-control"
				   type="password"
				   name="password"
				   placeholder="Password">
		</div>
		<input class="btn btn-primary"
			   type="submit"
			   value="Login">
	</form>

	Don't have anaccount?
	<a href="{% url "auctions:register" %}>Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

	<h2>Register</h2>

	{% if message %}
		<div>{{ message }}</div>
	{% endif %}

	<form action="{% url 'auctions:register' %}"
		  method="post">
		{% csrf_token %}
		<div class="form-group">
			<input class="form-control"
				   autofocus
				   type="text"
				   name="username"
				   placeholder="Username">
		</div>
		<div class="form-group">
			<input class="form-control"
				   type="email"
				   name="email"
				   placeholder="Email Address">
		</div>
		<div class="form-group">
			<input class="form-control"
				   type="password"
				   name="password"
				   placeholder="Password">
		</div>
		<div class="form-group">
			<input class="form-control"
				   type="password"
				   name="confirmation"
				   placeholder="Confirm Password">
		</div>
		<input class="btn btn-primary"
			   type="submit"
			   value="Register">
	</form>

	Already have an account?
	<a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block title %}
	Watchlist
{% endblock %}

{% block body %}
	<ul>
		<li>Listing 1</li>
		<li>Listing 2</li>
	</ul>
{% endblock %}