airline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("flights/", include("flights.urls")),
    path("users/", include("users.urls"))
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

users/models.py
# Create your models here.

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    return render(request, "users/login.html")


def login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username=username, password=password)

        if user:
            login(user)
            return HttpResponseRedirect(reverse("users:index"))
        else:
            return render(request, "users/login.html", {
                "message": "Invalid Credentials"
            })

    return render(request, "users/login.html")


def logout(request):
    logout(request)
    return render(request, "users/login.html", {
        "message": "Logged out"
    })

users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Users</title>
	</head>
	<body>
		{% block body %}

		{% endblock %}
	</body>
</html>

users/templates/users/login.html
{% extends "users/layout.html" %}

{% block body %}
	{% if message %}
		<div>{{ message }}</div>
	{% endif %}

	<form action="{% url "users:login" %}"
		  method="post">
		{% csrf_token %}
		<input type="text"
			   name="username"
			   placeholder="Username">
		<input type="password"
			   name="password"
			   placeholder="Password">
		<input type="submit"
			   value="Login">
	</form>
{% endblock %}

users/templates/users/user.html
{% extends "users/layout.html" %}

{% block body %}
	<h1>Welcome, {{ request.user.first_name }}</h1>
	<ul>
		<li>Username: {{ request.user.username }}</li>
		<li>Email: {{ request.user.email }}</li>
	</ul>
	<a href="{% url "logout" %}">Log out</a>
{% endblock %}