airline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("flights/", include("flights.urls")),
    path("users/", include("users.urls"))
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

flights/urls.py
from django.urls import path

from . import views

app_name = "flights"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:flight_id>", views.flight, name="flight"),
    path("<int:flight_id>/book", views.book, name="book")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

flights/models.py
from django.db import models


# Create your models here.

class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.city} ({self.code})"


class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()

    def __str__(self):
        return f"{self.id}: {self.origin} to {self.destination}"


class Passenger(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    flights = models.ManyToManyField(Flight, blank=True, related_name="passengers")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

flights/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Flight, Passenger


# Create your views here.

def index(request):
    return render(request, "flights/index.html", {
        "flights": Flight.objects.all()
    })


def flight(request, flight_id):
    flight = Flight.objects.get(id=flight_id)
    passengers = flight.passengers.all()
    non_passengers = Passenger.objects.exclude(flights=flight).all()
    return render(request, "flights/flight.html", {
        "flight": flight,
        "passengers": passengers,
        "non_passengers": non_passengers
    })


def book(request, flight_id):
    if request.method == "POST":
        flight = Flight.objects.get(pk=flight_id)
        passenger_id = int(request.POST["passenger"])
        passenger = Passenger.objects.get(pk=passenger_id)
        passenger.flights.add(flight)
        return HttpResponseRedirect(reverse("flights:flight", args=(flight.id,)))

flights/templates/flights/flight.html
{% extends "flights/layout.html" %}

{% block body %}
	<h1>Flight {{ flight.id }}</h1>
	<ul>
		<li>Origin: {{ flight.origin }}</li>
		<li>Destination: {{ flight.destination }}</li>
		<li>Duration: {{ flight.duration }}</li>
	</ul>
	<a href="{% url 'flights:index' %}">All Flights</a>
	<h2>Passengers:</h2>
	<ul>
		{% for passenger in passengers %}
			<li>{{ passenger }}</li>
		{% empty %}
			<li>No Passengers.</li>
		{% endfor %}
	</ul>
	<h2>Add passenger</h2>
	<form action="{% url "flights:book" flight.id %}"
		  method="post">
		{% csrf_token %}
		<select name="passenger"
				id="">
			{% for non_passenger in non_passengers %}
				<option value="{{ non_passenger.id }}">{{ non_passenger }}</option>
			{% endfor %}
		</select>
		<input type="submit">
	</form>
{% endblock %}

flights/templates/flights/index.html
{% extends "flights/layout.html" %}

{% block body %}
	<h1>Flights:</h1>
	<ul>
		{% for flight in flights %}
			<li>
				<a href="{% url 'flights:flight' flight.id %}">Flight {{ flight.id }}</a>
				: {{ flight.origin }}
				to {{ flight.destination }}
			</li>
		{% endfor %}
	</ul>
{% endblock %}

flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Flights</title>
	</head>
	<body>
		{% block body %}
		{% endblock %}
	</body>
</html>